# .github/workflows/deploy.yml
name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    # Don't run again when we push the built dist/ folder back
    paths-ignore:
      - 'dist/**'
      - '!.github/workflows/deploy.yml'  # still pick up changes to the workflow itself
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x,20.x,22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: ./dist
