# .github/workflows/deploy.yml
name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # 1) Check out the repo, keep credentials so we can push
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # 2) Install the specified Node.js version
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # 3) Install deps and build production bundle
      - name: Install dependencies & Build
        run: |
          npm ci
          npm run build

      # 4) Deploy the `dist/` folder to the `main` branch root
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main           # push back to main
          publish_dir: ./dist            # the folder Vite outputs
